dashboard/urls.py
from django.urls import path
from . import views

app_name = "profile"

urlpatterns = [
    path('', views.profile, name='profile'),
    path('biography/', views.biography, name='biography'),
    path('skills/', views.skills, name='skills'),
    path('projects/', views.projects, name='projects'),
    path('contact/', views.contact, name='contact'),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.conf import settings
from django.conf.urls.static import static

# from django.view.static import serve
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("dashboard.urls", namespace='dashboard'))

    # url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    # url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models

# Create your models here.
 
class Person(models.Model):
    id = models.CharField(primary_key=True,max_length=100)
    name = models.CharField(max_length=50)
    middle_name = models.CharField(max_length=50, default="None")
    surname = models.CharField(max_length=50)
    profile_caption = models.CharField(max_length=50, default="None")
    email = models.CharField(max_length=100)
    cell = models.CharField(max_length=10)
    description = models.TextField(max_length=1000)
    
    image = models.ImageField(upload_to='profiles')

    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Project(models.Model):
    id = models.CharField(primary_key=True,max_length=100)
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=1000)
    image = models.ImageField(upload_to='posters')
    
    link = models.CharField(max_length=1000, null=True)
    tags = models.ManyToManyField(Tag, blank=True)
    
    def __str__(self):
        return self.title

class Information(models.Model):
    information = models.TextField(max_length=1000)
    image = models.ImageField(upload_to='info')
    styleId = models.TextField(max_length=10)

    def __str__(self):
        return self.information

class Skill(models.Model):
    skill = models.TextField(max_length=50)
    rate = models.IntegerField()

    def __str__(self):
        return self.skill

dashboard/views.py
from django.shortcuts import render
from .models import Person, Project, Tag, Information, Skill
# Create your views here.

def profile(response):
    person = Person.objects.get(id='01')
    context = {'ps': person}
    return render(response, "dashboard/dashboard.html", context)

def biography(response):
    infomation = Information.objects.get(id='1')
    context = {'infomation': infomation}
    return render(response, "dashboard/biography.html", context)

def skills(response):
    skills = Skill.objects.all()
    tags = Tag.objects.all()
    context = {'skills': skills}
    return render(response, "dashboard/skills.html", context)

def projects(response):
    person = Person.objects.get(id='01')
    projects = Project.objects.all()
    context = {'proj': projects, 'ps': person}

    return render(response, "dashboard/projects.html", context)

def contact(response):
    person = Person.objects.get(id='01')
    context = {'ps': person}
    return render(response, "dashboard/contact.html", context)

def tags(response):
    tag = Person.objects.get(id='01')
    context = {'ps': person}
    return render(response, "dashboard/contact.html", context)

dashboard/templates/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
  <head>
    <title>Nkosinathi Mabuza</title>
    <link rel="stylesheet" href="{% static 'style.css' %}" />
    <link
      href="{% static 'fontawesomefree/css/all.min.css' %}"
      rel="stylesheet"
      type="text/css"
    />
    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@1,100&display=swap" rel="stylesheet">
  </head>

  <body class="root">
    <div class="side-nav">
      <a href="{% url 'profile:profile' %}">
        <div class="grp home">
          <i class="fa-solid fa-home fa-lg"></i>
        </div>
      </a>
      <a href="{% url 'profile:biography' %}">
        <div class="grp">
          <i class="fa-solid fa-circle-info fa-lg"></i>
        </div>
      </a>
      <a href="{% url 'profile:skills' %}">
        <div class="grp">
          <i class="fa-solid fa-chart-simple fa-lg"></i>
        </div>
      </a>
      <a href="{% url 'profile:projects' %}">
        <div class="grp">
          <i class="fa-solid fa-clipboard-list fa-lg"></i>
        </div>
      </a>
    </div>

    <div class="main">{% block body %} {% endblock body %}</div>
  </body>
</html>

dashboard/templates/dashboard/biography.html
{% extends 'base.html' %} {% block body %}

<div class="dash-Content">
  <h3>Biography</h3>

  <div class="bios">
    <h2>Hi, I'm <span class="hint"> Nkosinathi. </span></h2>

    <p>~ I'm a <span class="hint">Full-Stack</span> self - tought <span class="hint">Developer</span></p>
    
    <p>
      ~ Artificial Inteligence <span class="hint">AI/ML</span> and Internet Of Things <span class="hint">IOT</span> is amoung my favourit within the tech indeustry.
    </p>

    <p>
      ~ I am the the founder of <span class="hint">Simply Marrions.</span> A tech company
      aiming to building solutions that simplyfies our day to day lives.
    </p>

    <p>
      ~ Among my hobbies I am a <span class="hint">musician.</span> I play electric guitar,
      bass guitar and the piano.
    </p>
    <p>~ I love watching <span class="hint">SUB</span> anime</p>
  </div>
</div>
{% endblock body %}

dashboard/templates/dashboard/contact.html
{% extends 'base.html' %}

{% block body %}
<div class="dash-Content mycontact">
    <h3>Contact</h3>

    <div class="grp">
        <i class="fa-solid fa-mail-info fa-lg"></i>
        <p>Cell (primary): (068) 416 8106</p>
    </div>

    <div class="grp">
        <i class="fa-solid fa-cell-info fa-lg"></i>
        <p>Cell (secondary): (076) 415 0436</p>
    </div>

    <div class="grp">
        <i class="fa-solid fa-circle-info fa-lg"></i>
        <p>Email (primary): 77marrion@gmail.com</p>
    </div>

    <div class="grp">
        <i class="fa-solid fa-mail-info fa-lg"></i>
        <p>Email (secnodary): mabuza@petalmail.com</p>
    </div>

    <div class="grp">
        <i class="fa-brands fa-github-square"></i>
        <p>Github: MarrionNM</p>
    </div>

    <div class="grp">
        <i class="fa-brands fa-whatsapp-square"></i>
        <p>WhatsApp: (068) 416 8106</p>
    </div>

    <div class="grp">
        <i class="fa-brands fa-facebook-square"></i>
        <p>Facebook: Nkosinathi Mabuza</p>
    </div>


</div>
{% endblock body %}

dashboard/templates/dashboard/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block body %}

<div class="dash-Content dashboard">

    <div class="dash-Content-Caption">
        <img src="{{ ps.image.url }}" alt="Avatar">
        <h2>{{ ps.name }} {{ ps.middle_name }} {{ ps.surname }}</h2>
        <P>{{ ps.profile_caption }}</P>
    </div>

    <div class="dash-Content-services">
        <i class="fa-solid fa-envelope tooltip">
            <span class="tooltiptext">77marrion@gmail.com</span>
        </i>
        <i class="fa-solid fa-phone tooltip">
            <span class="tooltiptext">068-416-8106</span>
        </i>
        <!-- <i class="fa-brands fa-whatsapp"></i> -->
        <i class="fa-brands fa-facebook tooltip">
            <span class="tooltiptext">Nkosinathi Mabuza</span>
        </i>
        <i class="fa-brands fa-github tooltip">
            <span class="tooltiptext">MarrionNM</span>
        </i>
        <i class="fa-brands fa-linkedin tooltip">
            <span class="tooltiptext">Nkosinathi Mabuza</span>
        </i>
    </div>
</div>


{% endblock body %}

dashboard/templates/dashboard/projects.html
{% extends 'base.html' %} {% block body %}

<div class="dash-Content">
  <h3>Projects</h3>
  <div class="container projects">
    {% for project in proj %}
    <div class="card">
      <div class="card-imgs">
        <img src="{{project.image.url}}" alt="" />
      </div>

      <div class="card-data">
        <a href="{{project.link}}" target="blank"><h3>{{project.title}}</h3></a>
        <p>{{project.description}}</p>
      </div>
      <div class="card-tags">
        {% for tag in project.tags.all %}
        <img src="{{tag}}" alt="" />
        {% endfor %}
      </div>
    </div>
    {% endfor %}
  </div>
  <br/>
</div>
{% endblock body %}

dashboard/templates/dashboard/skills.html
{% extends 'base.html' %} {% block body %}

<div class="dash-Content skills">
  {% block scripts %}

  <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
  <script>
    AOS.init({
      duration: 1500,
    });
  </script>

  {% endblock scripts %}

  <h3>Skills</h3>

  <div>
    <!-- <div class="skills-tags">
      {% for skill in skills %}
      <img src="{{skill}}" alt="p" />
      {% endfor %}
    </div> -->

    <div class="skills-container">
      {% for skill in skills %}
      <div class="skill">
        <div class="info">
          <span>{{skill.skill}}</span>
          <span>{{skill.rate}}%</span>
        </div>
        <div class="bar">
          <div class="barfill" style="width: {{skill.rate}}%;"></div>
        </div>
      </div>
      {% endfor %}
      <br/>
    </div>

  </div>
  {% endblock body %}
</div>